version: "3"

services:
  vote:
    build: ./vote
    command: 
    - python 
    - app.py
    ports:
      - "5000:80"
    depends_on:
      - "redis"
      - "db"

  result:
    build: ./result
    command: 
    - nodemon 
    - server.js
    ports:
      - "5001:80"
    depends_on:
      - "redis"
      - "db"

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
      - "db"

  redis:
    image: redis:alpine

  db:
    image: postgres:9.4
